from . import *

global x

@Pbx_cmd(pattern="stopbiggspam$")
async def _(event):
    await eor(event, "Stopped Big Gaali Spam!")
    global x
    x = False


@Pbx_cmd(pattern="biggspam$")
async def _(event):
    global x
    x = True
    while x == True:
        await event.delete()
        chat = event.chat_id
        await Pbxbot.send_message(chat, "SHURU")
        await Pbxbot.send_message(chat, "KARU")
        await Pbxbot.send_message(chat, "TERI XHUDAI")
        await Pbxbot.send_message(chat, "TERIII")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "XHODD")
        await Pbxbot.send_message(chat, "TERII MAA")
        await Pbxbot.send_message(chat, "KA LUND")
        await Pbxbot.send_message(chat, "XHAKKE")
        await Pbxbot.send_message(chat, "TERIIIIII")
        await Pbxbot.send_message(chat, "MAA ")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "BHOSDA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "XHOD")
        await Pbxbot.send_message(chat, "DIYA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat,  "RANDI")
        await Pbxbot.send_message(chat, "HIJDE")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "BACCHA")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI") 
        await Pbxbot.send_message(chat, "CHUDAI")
        await Pbxbot.send_message(chat, "KI") 
        await Pbxbot.send_message(chat, "STORY")
        await Pbxbot.send_message(chat, "PADEGA")
        await Pbxbot.send_message(chat, "BOL")
        await Pbxbot.send_message(chat, "RAMDI KE BACCHE")
        await Pbxbot.send_message(chat, "TRRI")
        await Pbxbot.send_message(chat,  "MA")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "AASIQ")
        await Pbxbot.send_message(chat, "HOON")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat,  "MA")                                                     
        await Pbxbot.send_message(chat,   "KA")
        await Pbxbot.send_message(chat, "GANG")
        await Pbxbot.send_message(chat, "BANG")
        await Pbxbot.send_message(chat, "KARDU")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KO")
        await Pbxbot.send_message(chat, "PREGNANT") 
        await Pbxbot.send_message(chat, "KARDU")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "BEHAN")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "AASIQ") 
        await Pbxbot.send_message(chat, "HOON")   
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "PRICE")
        await Pbxbot.send_message(chat, "BOL")
        await Pbxbot.send_message(chat, "69$")
        await Pbxbot.send_message(chat, "DUNGA")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "TU")
        await Pbxbot.send_message(chat, "BATA")
        await Pbxbot.send_message(chat, "KITNE")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "DEGA")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, " BEHAN KI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "TERI") 
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "BHOSDA")
        await Pbxbot.send_message(chat, "FAT")
        await Pbxbot.send_message(chat, "GYA")
        await Pbxbot.send_message(chat, "JAAKE DEKH")
        await Pbxbot.send_message(chat,"TERI") 
        await Pbxbot.send_message(chat, "CHACHI")
        await Pbxbot.send_message(chat, "KO")
        await Pbxbot.send_message(chat,"BAGHA")
        await Pbxbot.send_message(chat, "LE")
        await Pbxbot.send_message(chat, "JAAU")
        await Pbxbot.send_message(chat, "BATA")
        await Pbxbot.send_message(chat, "LAWDE ")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "BEHAN")
        await Pbxbot.send_message(chat, "KO")
        await Pbxbot.send_message(chat, "OYO") 
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "CHODU")
        await Pbxbot.send_message(chat, "RANDI")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat, "BACCHE")
        await Pbxbot.send_message(chat, "DEMON")
        await Pbxbot.send_message(chat, "OR")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "BHOSDA")
        await Pbxbot.send_message(chat, "CHODU")
        await Pbxbot.send_message(chat, "GAY")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "BACCHA")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "maa")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "me")
        await Pbxbot.send_message(chat, "SAANP")
        await Pbxbot.send_message(chat, "GUSED")
        await Pbxbot.send_message(chat, "DU")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "GILI")
        await Pbxbot.send_message(chat, "CHUT")
        await Pbxbot.send_message(chat, "HAHAHAHAH")
        await Pbxbot.send_message(chat, "ABH")
        await Pbxbot.send_message(chat, "BOLDE")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "TERII")
        await Pbxbot.send_message(chat, "MAA")
        await Pbxbot.send_message(chat, "RANDI")   
        await Pbxbot.send_message(chat, "H")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat, "TATTE")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MAA")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat,  "SAATH")
        await Pbxbot.send_message(chat,  "SOJAAU")
        await Pbxbot.send_message(chat, "EK")
        await Pbxbot.send_message(chat, "NIGHT")
        await Pbxbot.send_message(chat, "BATA")
        await Pbxbot.send_message(chat, "BEHAN")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat, "LODE")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "NANGI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "AALU")
        await Pbxbot.send_message(chat, "BAMB")
        await Pbxbot.send_message(chat, "BAXXHA")
        await Pbxbot.send_message(chat, "H")
        await Pbxbot.send_message(chat, "TU")
        await Pbxbot.send_message(chat, " HAHAHAHAHA")
        await Pbxbot.send_message(chat, "BAAP")
        await Pbxbot.send_message(chat, "SE")
        await Pbxbot.send_message(chat, "LADEGA")
        await Pbxbot.send_message(chat, "ABH")
        await Pbxbot.send_message(chat, "TU")
        await Pbxbot.send_message(chat, "AUKAT")
        await Pbxbot.send_message(chat, "BANA")
        await Pbxbot.send_message(chat, "KIDXXX")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "RAPE")
        await Pbxbot.send_message(chat, "KARXUNGA")
        await Pbxbot.send_message(chat, "VERNA")
        await Pbxbot.send_message(chat, "HIHIHIHIHI")
        await Pbxbot.send_message(chat, "XHUD")
        await Pbxbot.send_message(chat, "GYI")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MUMMY")
        await Pbxbot.send_message(chat, "ABH")
        await Pbxbot.send_message(chat, "AAA")
        await Pbxbot.send_message(chat, "TU")
        await Pbxbot.send_message(chat, "SPEED")
        await Pbxbot.send_message(chat, "COVER")
        await Pbxbot.send_message(chat, "KAR")
        await Pbxbot.send_message(chat, "BAS")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MUMMY")
        await Pbxbot.send_message(chat, "XHOD")
        await Pbxbot.send_message(chat, "DUNGA")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, " AMMA")
        await Pbxbot.send_message(chat, "KA")
        await Pbxbot.send_message(chat, "AASIQ")
        await Pbxbot.send_message(chat, "BOL")
        await Pbxbot.send_message(chat, "MEKO")
        await Pbxbot.send_message(chat, "HAHAHAH")
        await Pbxbot.send_message(chat, "XHUD GYA")
        await Pbxbot.send_message(chat, "TU")
        await Pbxbot.send_message(chat, "TERA")
        await Pbxbot.send_message(chat, "KHANDAAN")
        await Pbxbot.send_message(chat, "XHOD")
        await Pbxbot.send_message(chat, "DAALA")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "BIWI")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "SE")
        await Pbxbot.send_message(chat, "BACCHA")
        await Pbxbot.send_message(chat, "NIKAL") 
        await Pbxbot.send_message(chat, "JAYEGAA")
        await Pbxbot.send_message(chat, "KALAP MAT")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MAA")
        await Pbxbot.send_message(chat, "SE")
        await Pbxbot.send_message(chat, "POOXH")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "TERA")
        await Pbxbot.send_message(chat, "ASLI")
        await Pbxbot.send_message(chat, "BAAP")
        await Pbxbot.send_message(chat, "KON")
        await Pbxbot.send_message(chat, "H")
        await Pbxbot.send_message(chat, "TERII")
        await Pbxbot.send_message(chat, "MUMMY")
        await Pbxbot.send_message(chat, "KI") 
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "SODA")
        await Pbxbot.send_message(chat, "GUSED")
        await Pbxbot.send_message(chat, "DU")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "BEHAN")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "XHUT")
        await Pbxbot.send_message(chat, "me")
        await Pbxbot.send_message(chat, "LIGHT")
        await Pbxbot.send_message(chat, "BULB")
        await Pbxbot.send_message(chat, "DAAL")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat, "SWITCH")
        await Pbxbot.send_message(chat, "ON") 
        await Pbxbot.send_message(chat, "KARDU")
        await Pbxbot.send_message(chat, "TERE")
        await Pbxbot.send_message(chat, "BAAP")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "MUMMY")
        await Pbxbot.send_message(chat,  "KE")
        await Pbxbot.send_message(chat, "BETE")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "BETI")
        await Pbxbot.send_message(chat, "XHOD")
        await Pbxbot.send_message(chat, "du")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MA")
        await Pbxbot.send_message(chat, "KI")
        await Pbxbot.send_message(chat, "CHUT")
        await Pbxbot.send_message(chat, "ME")
        await Pbxbot.send_message(chat, "LODA")
        await Pbxbot.send_message(chat, "DAAL")
        await Pbxbot.send_message(chat, "KE")
        await Pbxbot.send_message(chat, "MUTH")
        await Pbxbot.send_message(chat, "MAARDU")
        await Pbxbot.send_message(chat, "TERI")
        await Pbxbot.send_message(chat, "MAAAA")
        await Pbxbot.send_message(chat, "BEHAN")
        await Pbxbot.send_message(chat, "RANDI")
        await Pbxbot.send_message(chat, "TERA")
        await Pbxbot.send_message(chat, "PURA")
        await Pbxbot.send_message(chat, "KHANDAAN")
        await Pbxbot.send_message(chat, "XHOD")
        await Pbxbot.send_message(chat, "DAALA")
        await Pbxbot.send_message(chat, "HAHAHAHAH")


CmdHelp("biggspam").add_command(
    "biggspam", None, "Big Gaali Spam!"
).add_command(
    "stopbiggspam", None, "Big gaali spam stop!"
).add_warning(
    "May get floodwait!"
).add_info(
    "Spammer Module"
).add()
